document.addEventListener('DOMContentLoaded',()=>{
  const header=document.querySelector('.site-header'),progress=document.querySelector('#progress'),toggle=document.querySelector('#menuToggle'),mobile=document.querySelector('#mobileNav'),toast=document.querySelector('#toast');
  const update=()=>{const total=document.documentElement.scrollHeight-window.innerHeight;if(progress)progress.style.width=`${total>0?(scrollY/total)*100:0}%`;header?.classList.toggle('scrolled',scrollY>20)};addEventListener('scroll',update,{passive:true});update();
  toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));mobile?.classList.toggle('open',!open)});mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{toggle?.setAttribute('aria-expanded','false');mobile?.classList.remove('open')}));
  document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
  const show=message=>{if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)};
  document.querySelector('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();show('Thanks — you are on the Nexa-hub early access list.');e.target.reset()});document.querySelectorAll('.prompt-send,.prompt-line').forEach(el=>el.addEventListener('click',()=>show('Nexa-hub is getting ready — your workspace is coming soon.')));
  document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'})}}));
  const revealables=document.querySelectorAll('.process-step,.feature-card,.audience-card,.product-row,.split-section,.cta-card,.process-chat');revealables.forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',`${Math.min(i*55,280)}ms`)});if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});revealables.forEach(el=>observer.observe(el))}else revealables.forEach(el=>el.classList.add('is-visible'));
  const form=document.querySelector('#processChatForm'),input=document.querySelector('#processChatInput'),log=document.querySelector('#processChatLog');
  const replies={"What happens first?":"Start with the raw idea: a question, draft, or half-formed thought. You do not need a perfect prompt.","Help me shape an idea":"Put the idea on the table, then look for the useful shape: the goal, the tension, and the clearest direction.","What is the next move?":"Leave with something you can use: a decision, a plan, a first draft, or simply a better question."};
  const addMessage=(text,role)=>{if(!log)return;const item=document.createElement('div');item.className=`process-chat-message ${role}`;item.textContent=text;log.appendChild(item);log.scrollTop=log.scrollHeight;return item};
  const ask=question=>{if(!question)return;addMessage(question,'user');const typing=addMessage('Thinking…','bot typing');window.setTimeout(()=>{typing?.remove();addMessage(replies[question]||'Try breaking the idea into three parts: where you are, what you want, and the smallest useful next step.','bot')},420)};
  document.querySelectorAll('[data-chat-question]').forEach(button=>button.addEventListener('click',()=>ask(button.dataset.chatQuestion)));form?.addEventListener('submit',event=>{event.preventDefault();const question=input.value.trim();if(!question)return;input.value='';ask(question)});
});
