document.addEventListener('DOMContentLoaded',()=>{
  const orb=document.querySelector('#voiceOrb'),stage=document.querySelector('#orbStage'),state=document.querySelector('#assistantState'),prompt=document.querySelector('#voicePrompt'),transcript=document.querySelector('#transcript'),intentTitle=document.querySelector('#intentTitle'),intentDetail=document.querySelector('#intentDetail'),intentCard=document.querySelector('#intentCard'),confidence=document.querySelector('#confidence'),recentList=document.querySelector('#recentList'),historyCount=document.querySelector('#historyCount'),demo=document.querySelector('#demoButton'),clear=document.querySelector('#clearButton'),toast=document.querySelector('#toast');
  const examples=['افتح YouTube','قداش عندي بطارية؟','اعمللي timer عشرة دقايق','احسب 250 في 4','اكتب note نراجع اقتصاد']; let history=[]; let recognition=null;
  const say=(message)=>{ if('speechSynthesis' in window){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(message);u.lang='ar-TN';u.rate=.95;speechSynthesis.speak(u)} };
  const showToast=(message)=>{if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(window.nexaToast);window.nexaToast=setTimeout(()=>toast.classList.remove('show'),3000)};
  const setState=(value,copy,active=false)=>{state.textContent=value;prompt.textContent=copy;stage.classList.toggle('listening',active)};
  const parse=(raw)=>{const text=raw.toLowerCase().trim(); const has=(...words)=>words.some(word=>text.includes(word));
    if(has('بطارية','batterie','battery')) return {intent:'BATTERY',label:'Battery check',detail:'البطارية الحالية: 73%',answer:'البطارية متاعك 73 بالمية.',confidence:'98%'};
    if(has('الساعة','وقت','heure','time')) return {intent:'TIME',label:'Current time',detail:'نقرألك الوقت الحالي',answer:`الوقت توا ${new Date().toLocaleTimeString('ar-TN',{hour:'2-digit',minute:'2-digit'})}.`,confidence:'96%'};
    if(has('احسب','calculate','حساب')){const nums=text.match(/\d+(?:[.,]\d+)?/g)?.map(Number)||[]; const result=nums.length>=2?nums[0]*nums[1]:'250 × 4 = 1000'; return {intent:'CALCULATE',label:'Calculator',detail:`النتيجة: ${typeof result==='number'?result:result}`,answer:`النتيجة هي ${typeof result==='number'?result:1000}.`,confidence:'99%'};}
    if(has('timer','تايمر','مؤقت','دقايق','minutes')){const match=text.match(/\d+/); const minutes=match?match[0]:'10'; return {intent:'TIMER',label:'Timer',detail:`باش نعمل Timer لمدة ${minutes} دقايق`,answer:`حاضر، عملتلك Timer لمدة ${minutes} دقايق.`,confidence:'97%'};}
    if(has('note','نوت','ملاحظة','اكتب','sajjel')) return {intent:'NOTE',label:'New note',detail:'باش نحفظ النص في Notes متاع Nexa',answer:'حاضر، حفظت الملاحظة في Notes متاعك.',confidence:'94%'};
    if(has('youtube','يوتيوب')) return {intent:'OPEN_APP',label:'Open YouTube',detail:'باش نفتح تطبيق YouTube',answer:'حاضر، حلّيتلك YouTube.',confidence:'99%'};
    if(has('camera','كاميرا','صوّر')) return {intent:'OPEN_APP',label:'Open Camera',detail:'باش نفتح الكاميرا',answer:'حاضر، فتحتلك الكاميرا.',confidence:'99%'};
    if(has('settings','إعدادات','paramètres','bluetooth')) return {intent:'SETTINGS',label:'Open Settings',detail:'باش نفتح إعدادات الجهاز',answer:'حاضر، نحلّك Settings.',confidence:'95%'};
    return {intent:'UNKNOWN',label:'Need another try',detail:'ما لقيتش أمر واضح — جرّب جملة أقصر أو اختار مثال من تحت.',answer:'سامحني، ما فهمتش الأمر توا. جرّب صياغة أخرى.',confidence:'42%'};
  };
  const renderHistory=()=>{historyCount.textContent=`${history.length} command${history.length===1?'':'s'}`; if(!history.length){recentList.innerHTML='<div class="empty-history">مازال ما فما حتى أمر — ابدأ بأول تجربة.</div>';return} recentList.innerHTML=history.slice().reverse().map(item=>`<div class="recent-item"><span class="recent-symbol">${item.intent==='BATTERY'?'◒':item.intent==='TIMER'?'◷':item.intent==='CALCULATE'?'×':item.intent==='NOTE'?'✎':'↗'}</span><div><strong>${item.label}</strong><small>${item.text}</small></div><time>${item.time}</time></div>`).join('')};
  const run=(raw)=>{const result=parse(raw); transcript.textContent=`“${raw}”`;intentTitle.textContent=result.label;intentDetail.textContent=result.detail;confidence.textContent=result.confidence;intentCard.dataset.intent=result.intent;history.push({...result,text:raw,time:new Date().toLocaleTimeString('en',{hour:'2-digit',minute:'2-digit'})});renderHistory();setState('COMMAND COMPLETE',result.answer,false);showToast(result.answer);say(result.answer)};
  const listen=()=>{if(!recognition){showToast('المتصفح متاعك ما يدعمش Voice Recognition — استعمل الأمثلة من تحت.');return} try{recognition.start()}catch(e){}};
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition; if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='ar-TN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{setState('LISTENING…','نسمع فيك توا',true);transcript.textContent='…';};recognition.onresult=(event)=>{const text=Array.from(event.results).map(r=>r[0].transcript).join('');transcript.textContent=`“${text}”`;if(event.results[0].isFinal){setState('UNDERSTANDING…','نحلّل الأمر',false);setTimeout(()=>run(text),350)}};recognition.onerror=()=>{setState('READY TO LISTEN','عاود جرّب أو استعمل مثال',false);showToast('ما نجّمتش نسمع الصوت — تأكد من الميكروفون.')};recognition.onend=()=>{if(state.textContent==='LISTENING…')setState('READY TO LISTEN','اضغط على الدائرة واحكي',false)}};
  orb?.addEventListener('click',listen); demo?.addEventListener('click',()=>run(examples[Math.floor(Math.random()*examples.length)])); clear?.addEventListener('click',()=>{history=[];renderHistory();transcript.textContent='“شنوة تحبني نعمل؟”';intentTitle.textContent='جاهز نسمعك';intentDetail.textContent='جرّب: “قدّاش عندي بطارية؟” أو “اعمللي Timer عشرة دقايق”.';confidence.textContent='—';setState('READY TO LISTEN','اضغط على الدائرة واحكي',false)});document.querySelectorAll('[data-voice-command]').forEach(button=>button.addEventListener('click',()=>run(button.dataset.voiceCommand)));renderHistory();
});
